const CLOUDINARY_CLOUD_NAME = 'dm9hihcwt'
const CLOUDINARY_CLOUD_API_KEY = '457789658564765'
const CLOUDINARY_CLOUD_API_SECRET = 'A6BTi_DzcCvuoNX8cOY2mPrv-Xs'


module.exports = { CLOUDINARY_CLOUD_NAME, CLOUDINARY_CLOUD_API_KEY, CLOUDINARY_CLOUD_API_SECRET }